on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages and test deps
        run: pip install -e .[test]

      - name: Run pytest
        run: pytest
